services:
  app:
    build: .
    container_name: vaccume-server
    restart: unless-stopped

    ports:
      - '${APP_PORT}:${PORT}'

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public

      # NestJS listens on the same port as defined in .env
      PORT: ${PORT}

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - app-network

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped

    ports:
      - '${POSTGRES_PORT}:5432'

    env_file:
      - .env

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
